# Crowdin config
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

# Base paths
base_path: .
base_url: https://api.crowdin.com

# File structure in Crowdin
preserve_hierarchy: true

# Files configuration
files:
  - source: web/en.json
    translation: web/%two_letters_code%.json
    scheme: file-based
    type: json

  - source: desktop/en.json
    translation: desktop/%two_letters_code%.json
    scheme: file-based
    type: json
