project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 
files:
  - source: web/en.json
    translation: web/%two_letters_code%.json
    scheme: file-based
    type: json
  - source: desktop/en.json
    translation: desktop/%two_letters_code%.json
    scheme: file-based
    type: json
